options:
  formatter: stylish
  merge-default-rules: true
rules:
  border-zero: 1
  brace-style:
    - 1
    - allow-single-line: true
  class-name-format:
    - 1
    - convention: hyphenatedbem
  clean-import-paths:
    - 1
    - filename-extension: false
      leading-underscore: false
  empty-line-between-blocks:
    - 1
    - ignore-single-line-rulesets: true
  extends-before-declarations: 1
  extends-before-mixins: 1
  final-newline:
    - 1
    - include: true
  function-name-format:
    - 1
    - convention: hyphenatedlowercase
  hex-length:
    - 1
    - style: long
  hex-notation:
    - 1
    - style: lowercase
  id-name-format:
    - 1
    - convention: hyphenatedlowercase
  indentation: 1
  leading-zero:
    - 1
    - include: true
  mixin-name-format:
    - 1
    - convention: hyphenatedlowercase
  mixins-before-declarations:
    - 1
    -
      exclude:
        - media
  nesting-depth:
    - 1
    - max-depth: 3
  no-color-keywords: 1
  no-css-comments: 0
  no-debug: 1
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-ids: 1
  no-invalid-hex: 1
  no-important: 1
  no-mergeable-selectors: 1
  no-misspelled-properties:
    - 1
    - extra-properties: []
  no-qualifying-elements:
    - 1
    - allow-element-with-attribute: true
      allow-element-with-class: true
      allow-element-with-id: false
  no-trailing-zero: 1
  no-url-protocols: 1
  placeholder-in-extend: 1
  placeholder-name-format:
    - 1
    - convention: hyphenatedlowercase
  property-sort-order: 0
  quotes:
    - 1
    - style: single
  shorthand-values: 1
  single-line-per-selector: 1
  space-after-bang:
    - 1
    - include: false
  space-after-colon:
    - 1
    - include: true
  space-after-comma: 1
  space-before-bang:
    - 1
    - include: true
  space-before-brace:
    - 1
    - include: true
  space-before-colon: 1
  space-between-parens:
    - 1
    - include: false
  trailing-semicolon: 1
  url-quotes: 1
  variable-name-format:
    - 1
    - convention: hyphenatedlowercase
  zero-unit: 1
